<a href="https://colab.research.google.com/github/chetansoni1569/DATA-SC/blob/main/Day_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
#NUMPY
import numpy as np

In [13]:
a= np.array([1,3,9,0,'hello'])
print(a)

['1' '3' '9' '0' 'hello']


In [17]:
np_arr =np.array([3,3,3.33,'hello',False])
print(bool(np_arr[-1]))

a=False
print (bool(a))

True
False


In [24]:
a= np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [25]:
#matrix
a= np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [27]:
a= np.zeros((2,3,4))
print(a)

print(type(a[0][0][0]))

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<class 'numpy.float64'>


In [28]:
a= np.zeros((2,3,4), dtype=int)
print(a)

print(type(a[0][0][0]))

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
<class 'numpy.int64'>


In [29]:
a= np.ones((2,3,4))
print(a)

print(type(a[0][0][0]))

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
<class 'numpy.float64'>


In [30]:
#empty.  (give garbage value)
a=np.empty(4, dtype=int)
print(a)

[      123430654               0             112 136414043720944]


In [31]:
a=np.full(4,5,dtype=int)
print(a)

[5 5 5 5]


In [37]:
a= np.full((2,9), 0)
print(a)

[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


In [38]:
a=np.arange(3,12,4)
#3 to 12 range and 4 value jump
print(a)

[ 3  7 11]


In [43]:
a=np.linspace(3,12,4, dtype=int, endpoint=False)
#by default endpoint is true it means it includes the last value
print(a)

[3 5 7 9]


In [47]:
a= np.random.randint(1,7,4)
#frpom 1 to 7 it give random values..
print (a)

[1 2 2 4]


In [56]:
a=np.random.choice([2,4,2,9],2)
print (a)

[9 4]


In [64]:
a=np.array([1,3,5,6,8,9])
b=np.array([3,4,5,6,7,7])
print(a*2)
print(a+b)
print(a%b)
print(a-b)



[ 2  6 10 12 16 18]
[ 4  7 10 12 15 16]
[1 3 0 0 1 2]
[-2 -1  0  0  1  2]


In [67]:
lst=[2,3,4,5,6]
print(lst*2)

[2, 3, 4, 5, 6, 2, 3, 4, 5, 6]


In [68]:
lst1=[1,2,3,4,5]
lst2=[2,3,4,5,5]
print(lst1+lst2)

[1, 2, 3, 4, 5, 2, 3, 4, 5, 5]


In [ ]:
#concatenate
#transpose
#where
#sort
#sum
#mean
#std
#min
#max
#unique


In [70]:
a=np.random.randint(2,15,6)
b=np.random.randint(1,19,6)

print(np.concatenate((a,b)))

[13 10  3 14  9 11  2  6  8  5 16  9]


In [76]:
a=np.random.randint(2,15,6)
b=np.random.randint(1,19,6)
print(a)
print(b)
c=np.where(b>2,b,a)
print(c)

[10  6  7 12  7  9]
[15  8  3  1 10 16]
[15  8  3 12 10 16]
