<a href="https://colab.research.google.com/github/chetansoni1569/DATA-SC/blob/main/DAY_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#create a 5*5 matrix of random integer (1-90)

In [11]:
mat = np.random.randint(1, 91, size=(5, 5))
print("matrix: ",mat)


#find the mean value row and col wise
row_wisw_mean=np.mean(mat,axis=1)
col_wisw_mean=np.mean(mat,axis=0)

print("rowwise mean: ", row_wisw_mean)
print("colwise mean: ", col_wisw_mean)

#replace  all even number with -1;

modified_mat=np.where(mat%2==0,-1,mat)
print("modified matrix: ",modified_mat)

#sort the array row and column wise
sorted_row_wise=np.sort(mat,axis=1)
sorted_col_wise=np.sort(mat,axis=0)
print("sorted row wise: ",sorted_row_wise)
print("sorted col wise: ",sorted_col_wise)

#find row and colum wise sum seperately
row_wise_sum=np.sum(mat,axis=1)
col_wise_sum=np.sum(mat,axis=0)

print("row wise sum: ",row_wise_sum)
print("col wise sum: ",col_wise_sum)

#count the number of negative in each column
count_col =np.sum(np.where(mat<0,1,0), axis=0)
print(count_col)

print("number of negative in each column: ",count_col)



matrix:  [[40 41 14  1 55]
 [49  9 57 45 81]
 [56 44 49 16 79]
 [18  2 53 42 62]
 [ 2 25 82 85 37]]
rowwise mean:  [30.2 48.2 48.8 35.4 46.2]
colwise mean:  [33.  24.2 51.  37.8 62.8]
modified matrix:  [[-1 41 -1  1 55]
 [49  9 57 45 81]
 [-1 -1 49 -1 79]
 [-1 -1 53 -1 -1]
 [-1 25 -1 85 37]]
sorted row wise:  [[ 1 14 40 41 55]
 [ 9 45 49 57 81]
 [16 44 49 56 79]
 [ 2 18 42 53 62]
 [ 2 25 37 82 85]]
sorted col wise:  [[ 2  2 14  1 37]
 [18  9 49 16 55]
 [40 25 53 42 62]
 [49 41 57 45 79]
 [56 44 82 85 81]]
row wise sum:  [151 241 244 177 231]
col wise sum:  [165 121 255 189 314]
[0 0 0 0 0]
number of negative in each column:  [0 0 0 0 0]


In [32]:
import numpy as np
#create a 5*5 array (stock level)
# create another 5*5 array (demand)

arr1= np.random.randint(1, 100, size=(5, 5))
arr2= np.random.randint(1, 100, size=(5, 5))

print("arr1: ",arr1)
print("arr2: ",arr2)

#compute:
#remaning stock= stock-demand
remaning_stock= arr1-arr2
print("remaning_stock: ",remaning_stock)


#replace :
#nagative values ->0 (out of stock)
remaning_stock[remaning_stock<0]=0
print("remaning_stock: ",remaning_stock)

#find:
#totoal shortage
total_shortage= np.sum(remaning_stock[remaning_stock<0])
print("total_shortage: ",total_shortage)

#products with zero stock
zero_stock= np.where(remaning_stock==0)
print("zero_stock: ",zero_stock)

#sort each row based on remaning stock
sorted_remaning_stock= np.sort(remaning_stock, axis=1)
print("sorted_remaning_stock: ",sorted_remaning_stock)



arr1:  [[38 42 26 66 51]
 [45 62 69 48 23]
 [88 33 69 54 91]
 [20 39 36 39  9]
 [75  3  4 81 99]]
arr2:  [[72 18 18 90 92]
 [12 99 20 87 45]
 [46 92 56  4 98]
 [30 48  2 87 82]
 [52 95 33 46 13]]
remaning_stock:  [[-34  24   8 -24 -41]
 [ 33 -37  49 -39 -22]
 [ 42 -59  13  50  -7]
 [-10  -9  34 -48 -73]
 [ 23 -92 -29  35  86]]
remaning_stock:  [[ 0 24  8  0  0]
 [33  0 49  0  0]
 [42  0 13 50  0]
 [ 0  0 34  0  0]
 [23  0  0 35 86]]
total_shortage:  0
zero_stock:  (array([0, 0, 0, 1, 1, 1, 2, 2, 3, 3, 3, 3, 4, 4]), array([0, 3, 4, 1, 3, 4, 1, 4, 0, 1, 3, 4, 1, 2]))
sorted_remaning_stock:  [[ 0  0  0  8 24]
 [ 0  0  0 33 49]
 [ 0  0 13 42 50]
 [ 0  0  0  0 34]
 [ 0  0 23 35 86]]


In [33]:
#PANDAS-

In [37]:
import pandas as pd

file_= pd.read_csv('student_data.csv')
print(file_)



      study_hours  attendance  sleep_hours  internet_usage  \
0               7          56            8               7   
1               4          69            5               3   
2              11          60            7               6   
3               8          99            9               8   
4               5          52            8               6   
...           ...         ...          ...             ...   
9995            2          58            9               7   
9996            7          98            6               9   
9997           10          44            8               5   
9998           10          75            7               5   
9999            2          70            6              11   

      assignments_completed  previous_score  exam_score placement_status  
0                        10              62      100.00           Placed  
1                         8              56      100.00           Placed  
2                        10   

In [40]:
file_= pd.read_csv('student_data.csv', sep=',')
print(file_.head())

   study_hours  attendance  sleep_hours  internet_usage  \
0            7          56            8               7   
1            4          69            5               3   
2           11          60            7               6   
3            8          99            9               8   
4            5          52            8               6   

   assignments_completed  previous_score  exam_score placement_status  
0                     10              62      100.00           Placed  
1                      8              56      100.00           Placed  
2                     10              45      100.00           Placed  
3                      4              55       90.17           Placed  
4                      8              40       78.82           Placed  


In [41]:
file_= pd.read_csv('student_data.csv', sep=',')
print(file_.tail())

      study_hours  attendance  sleep_hours  internet_usage  \
9995            2          58            9               7   
9996            7          98            6               9   
9997           10          44            8               5   
9998           10          75            7               5   
9999            2          70            6              11   

      assignments_completed  previous_score  exam_score placement_status  
9995                      8              88       69.31       Not Placed  
9996                      4              87      100.00           Placed  
9997                     10              37       95.94           Placed  
9998                      8              52       88.61           Placed  
9999                     16              52       78.96           Placed  
